name: test-docker
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aioeasywebdav=2.4.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - amply=0.1.5
  - appdirs=1.4.4
  - async-timeout=4.0.2
  - attmap=0.13.2
  - attrs=22.1.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.2
  - boost-cpp=1.74.0
  - boto3=1.24.80
  - botocore=1.27.81
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cachetools=5.2.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cni=1.0.1
  - cni-plugins=1.0.1
  - coin-or-cbc=2.10.8
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.7
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - coincbc=2.10.8
  - colorama=0.4.5
  - commonmark=0.9.1
  - configargparse=1.5.3
  - connection_pool=0.0.3
  - contourpy=1.0.5
  - cryptography=37.0.4
  - cvxpy=1.2.1
  - cvxpy-base=1.2.1
  - cycler=0.11.0
  - dataclasses=0.8
  - datrie=0.8.2
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.19
  - dpath=2.0.6
  - dropbox=11.34.0
  - ecos=2.0.10
  - fastp=0.23.2
  - filechunkio=1.8
  - filelock=3.8.0
  - fonttools=4.37.3
  - freetype=2.12.1
  - freyja=1.3.10
  - frozenlist=1.3.1
  - ftputil=5.0.4
  - future=0.18.2
  - gitdb=4.0.9
  - gitpython=3.1.27
  - google-api-core=2.10.1
  - google-api-python-client=2.62.0
  - google-auth=2.11.1
  - google-auth-httplib2=0.1.0
  - google-cloud-core=2.3.2
  - google-cloud-storage=2.5.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.3.3
  - googleapis-common-protos=1.56.4
  - grpcio=1.46.0
  - htslib=1.16
  - httplib2=0.20.4
  - icu=70.1
  - idna=3.4
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - iniconfig=1.1.1
  - isa-l=2.30.0
  - ivar=1.3.1
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.2.0
  - jpeg=9e
  - jq=1.6
  - jsonschema=4.16.0
  - jupyter_core=4.11.1
  - k8=0.2.5
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libabseil=20220623.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcbor=0.9.0
  - libcrc32c=1.1.2
  - libcurl=7.83.1
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libfido2=1.11.0
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=12.1.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libprotobuf=3.20.1
  - libseccomp=2.4.4
  - libsodium=1.0.18
  - libsqlite=3.39.3
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libudev1=249
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.2
  - libzlib=1.2.12
  - logmuse=0.2.6
  - lz4-c=1.9.3
  - lzo=2.10
  - mafft=7.508
  - markupsafe=2.1.1
  - matplotlib-base=3.6.0
  - minimap2=2.24
  - mpi=1.0
  - multidict=6.0.2
  - munkres=1.1.4
  - mysql-connector-c=6.1.11
  - nbformat=5.6.1
  - ncurses=6.3
  - numpy=1.23.3
  - oauth2client=4.1.3
  - oniguruma=6.9.8
  - openjpeg=2.5.0
  - openmpi=4.1.2
  - openssh=9.0p1
  - openssl=1.1.1q
  - osqp=0.6.2.post0
  - packaging=21.3
  - pandas=1.5.0
  - paramiko=2.11.0
  - peppy=0.35.2
  - pillow=9.2.0
  - pip=22.2.2
  - pkgutil-resolve-name=1.3.10
  - plac=1.3.5
  - plotly=5.10.0
  - pluggy=1.0.0
  - ply=3.11
  - prettytable=3.4.1
  - protobuf=3.20.1
  - psutil=5.9.2
  - pthread-stubs=0.4
  - pulp=2.6.0
  - py=1.11.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.13.0
  - pynacl=1.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=7.1.3
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-irodsclient=1.1.5
  - python_abi=3.10
  - pytz=2022.2.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - qdldl-python=0.1.5
  - ratelimiter=1.2.0
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - retry=0.9.2
  - rich=12.5.1
  - rsa=4.9
  - s3transfer=0.6.0
  - samtools=1.15.1
  - scipy=1.9.1
  - scs=3.2.0
  - setuptools=65.4.0
  - setuptools-scm=7.0.5
  - singularity=3.8.6
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=6.2.0
  - smmap=3.0.5
  - squashfs-tools=4.4
  - stone=3.3.1
  - stopit=1.1.2
  - tabulate=0.8.10
  - tenacity=8.1.0
  - tk=8.6.12
  - tomli=2.0.1
  - toposort=1.7
  - tqdm=4.64.1
  - traitlets=5.4.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022d
  - ubiquerg=0.6.2
  - ucsc-fatovcf=426
  - unicodedata2=14.0.0
  - uritemplate=4.1.1
  - urllib3=1.26.11
  - usher=0.5.6
  - veracitools=0.1.3
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wrapt=1.14.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.7.2
  - yte=1.5.1
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
