"""
    module for testing aggregate rule
    generated by snakemake
    last edited 7-12-22
"""
import common


def test_aggregate():
    """
    function to test aggregate rule
    """

    additional_variable = [
        "--snakefile",
        "snakefile3",
    ]

    common.run_unit_test("aggregate", "endpoints/aggregate.done", additional_variable)
