"""
    module for testing mapping rule
    generated by snakemake
    last edited 11-21-22
"""
import common


def test_mapping():
    """
    function to test mapping rule
    """

    additional_variable = ["--snakefile", "snakefile1", "--config", "query=False"]

    common.run_unit_test("mapping", "sams/ERR9813149.sam.done", additional_variable)


if __name__ == "__main__":

    # Stand alone testing.  testfiles.tar.gz will need to be decompressed prior to running.
    # Must be run in the backend subdir to work.

    test_mapping()
