"""
    module for testing sam2bam rule
    generated by snakemake
    last edited 11-23-22
"""
import common


def test_sam2bam():
    """
    function to test sam2bam rule
    """

    additional_variable = [
        "--snakefile",
        "snakefile1",
    ]

    common.run_unit_test("sam2bam", "sams/SRR17866146.bam.done", additional_variable)
