"""
    module for testing vc rule
    generated by snakemake
    last edited 11-21-22
"""
import common


def test_vc():
    """
    function to test vc rule
    """

    additional_variable = [
        "--snakefile",
        "snakefile2",
    ]

    common.run_unit_test("vc", "endpoints/SRR17866146.tsv", additional_variable)
