"""
    module for testing get_fastqs rule
    generated by snakemake
    last edited 11-21-22
"""
import common


def test_get_fastqs():
    """
    function to test get_fastqs rule
    """

    additional_variable = ["--snakefile", "snakefile1", "--config", "query=False"]

    common.run_unit_test("get_fastqs", "fastqs/ERR9813149.fq.done", additional_variable)
