"""
    module for testing mapping rule
    generated by snakemake
    last edited 7-12-22
"""
import common


def test_mapping():
    """
    function to test mapping rule
    """

    additional_variable = [
        "--snakefile",
        "snakefile2",
    ]

    common.run_unit_test("mapping", "sams/ERR9813149.sam", additional_variable)


if __name__ == "__main__":

    # Stand alone testing.  testfiles.tar.gz will need to be decompressed prior to running.
    # Must be run in the backend subdir to work.

    test_mapping()
