"""
    module for testing mapping rule
    generated by snakemake
    last edited 7-12-22
"""
import common


def test_mapping():
    """
    function to test mapping rule
    """

    additional_variable = [
        "--snakefile",
        "snakefile2",
    ]

    common.run_unit_test("mapping", "sams/ERR9813149.sam", additional_variable)
