"""
    module for testing aggregate rule
    generated by snakemake
    last edited 11-21-22
"""
import common


def test_aggregate():
    """
    function to test aggregate rule
    """

    additional_variable = [
        "--snakefile",
        "snakefile2",
    ]

    common.run_unit_test("aggregate", "endpoints/aggregate.done", additional_variable)


if __name__ == "__main__":

    # Stand alone testing.  testfiles.tar.gz will need to be decompressed prior to running.
    # Must be run in the backend subdir to work.

    test_aggregate()
