"""
    module for testing consensus rule
    generated by snakemake
    last edited 11-21-22
"""
import common


def test_consensus():
    """
    function to test consensus rule
    """

    additional_variable = [
        "--snakefile",
        "snakefile2",
    ]

    common.run_unit_test("consensus", "endpoints/SRR17866146.fa", additional_variable)
