"""
    module for testing download_sra rule
    generated by snakemake
    last edited 7-12-22
"""

import common


def test_download_sra():
    """
    function to test download_sra rule
    """

    additional_variable = [
        "--config",
        "query=ERR9812480+or+SRR14010117",
        "run_ID=test",
        "--snakefile",
        "snakefile1",
    ]

    common.run_unit_test("download_sra", "download_sra", additional_variable)
