"""
    module for testing download_sra rule
    generated by snakemake
    last edited 11-21-22
"""

import common


def test_download_sra():
    """
    function to test download_sra rule
    """

    additional_variable = [
        "--config",
        "query=ERR9812480+or+SRR14010117",
        "run_ID=test",
        "--snakefile",
        "snakefile1",
        "--resources",
        "download_streams=2",
    ]

    common.run_unit_test(
        "download_sra", "SRAs/SRR14010117.sra.done", additional_variable
    )
